services:
  pa_datagrid.filter.boolean:
    class: PaLabs\DatagridBundle\DataSource\Doctrine\Filter\Type\BooleanFilter
    tags: ['pa_datagrid.filter']

  pa_datagrid.filter.date:
    class: PaLabs\DatagridBundle\DataSource\Doctrine\Filter\Type\DateFilter
    tags: ['pa_datagrid.filter']

  pa_datagrid.filter.entity:
    class: PaLabs\DatagridBundle\DataSource\Doctrine\Filter\Type\EntityFilter
    tags: ['pa_datagrid.filter']

  pa_datagrid.filter.integer:
    class: PaLabs\DatagridBundle\DataSource\Doctrine\Filter\Type\IntegerFilter
    tags: ['pa_datagrid.filter']

  pa_datagrid.filter.string:
    class: PaLabs\DatagridBundle\DataSource\Doctrine\Filter\Type\StringFilter
    tags: ['pa_datagrid.filter']

  pa_datagrid.filter.collection_emptiness:
    class: PaLabs\DatagridBundle\DataSource\Doctrine\Filter\Type\CollectionEmptinessFilter
    tags: ['pa_datagrid.filter']

  pa_datagrid.filter.integer_having:
    class: PaLabs\DatagridBundle\DataSource\Doctrine\Filter\Type\IntegerHavingFilter
    tags: ['pa_datagrid.filter']

  pa_datagrid.filter.in_null:
    class: PaLabs\DatagridBundle\DataSource\Doctrine\Filter\Type\IsNullFilter
    tags: ['pa_datagrid.filter']